### ISSUE TITLE
Request to change from java.time.Duration to java.util.Calendar for hand rotation on WatchFaceKotlin

### ISSUE THREAD

**Issue by lancelinksp** [android/wear-os-samples#326]
Please use java.util.Calendar for time on the WatchFaceKotlin sample. This is what almost every watch face our there is using. Unless you can show how to also implement smooth seconds using java.time.Duration (I can't figure it out :P.  Please don't make it more difficult for developers since I can find no documentation for how to implement this.

**Comment by yschimke** [comment]
Could you expand a bit on it, is it the use of `val secondsPerSecondHandRotation = Duration.ofMinutes(1).seconds`

https://github.com/android/wear-os-samples/blob/0ab647531c891e7e8f0bc821fc178d8fdd10e4ca/WatchFaceKotlin/app/src/main/java/com/example/android/wearable/alpha/AnalogWatchCanvasRenderer.kt#L262-L337

Or something else.

Perhaps a microbenchmark here might help to validate any API changes we make, since this seems to be driven by performance.  

Or it this about Duration.seconds being too granular?

**Comment by lancelinksp** [comment]
I guess maybe my request is possibly due to the fact that I can't seem to figure out how to use this different api to calculate smooth second hand rotation versus ticking where in the past with java.util.Calendar it seemed pretty straight forward. Maybe it's just me 🤷

**Comment by yschimke** [comment]
Ahhh, that works perfectly fine. This is not optimized, but just to show how you can use nano from the LocalTime 

```
                val nanoOfSeconds = localTime.nano.toFloat() / Duration.ofSeconds(1).toNanos()

                val secondsAsFloat =
                    secondOfDay.rem(secondsPerSecondHandRotation).toFloat() + nanoOfSeconds
                val secondsRotation = secondsAsFloat * 360.0f / secondsPerSecondHandRotation
```

Going to close this out then.

**Comment by lancelinksp** [comment]
Thanks, I definitely didn't try that

**Comment by lancelinksp** [comment]
If I try to use localTime.nano.toFloat() then localTime doesnt resolve. If I change to LocalTime.nano.toFloat() and import java.time.LocalTime then nano is unresolved. If I try to change that from LocalTime.nano.toFloat() to  LocalTime.ofNanoOfDay.toFloat() does not work either. What am I missing?

**Comment by yschimke** [comment]
This is the diff I tested with https://github.com/yschimke/wear-os-samples/commit/c22b3e60dde34d0e9e4f33a1df9ef104eecf2f4f

**Comment by lancelinksp** [comment]
Thank you, very helpful. I appreciate your assistance
