### ISSUE TITLE
XYZ Tourist Attractions can't be installed on wear device

### ISSUE THREAD

**Issue by norekluk** [android/wear-os-samples#37]
I am getting this while trying to deploy the weareable module on my watch. "Warning: The activity must be exported or contain an intent-filter". I searched the internet and added this: ` <intent-filter>
                <action android:name="android.intent.action.MAIN" />
            </intent-filter>` to AndroidManifest.xml but that deployed weird app that looks like the handheld one and doesn't feel like weareble compatible. The deployment guides didn't really helped with this issue.

**Comment by codingjeremy** [comment]
Thanks for logging the issue! 

That app was originally developed for the first versions of Wear 1.0 quite a few years ago. I have deprecated it, since it doesn't follow best practices.

We are in the process of updating many of the samples and adding Kotlin samples. Hopefully, that will cover the use case you had. Let us know if not.
