### ISSUE TITLE
WearVerifyRemoteApp sample should avoid use of NodeClient

### ISSUE THREAD

**Issue by yschimke** [android/wear-os-samples#505]
https://github.com/android/wear-os-samples/blob/d18c489ff415aa0fbb25c260e3aacdf50f7716e3/WearVerifyRemoteApp/Application/src/main/java/com/example/android/wearable/wear/wearverifyremoteapp/MainMobileActivity.kt

https://developers.google.com/android/reference/com/google/android/gms/wearable/NodeClient

> New code should use [CapabilityClient](https://developers.google.com/android/reference/com/google/android/gms/wearable/CapabilityClient) which allows you to create and listen to application-specific network events.

**Comment by luizgrp** [comment]
@yschimke the title of this issue says "DataLayer sample" but the link in the description points tot the "WearVerifyRemoteApp" sample. Could you please clarify which sample should be updated? Both?

**Comment by luizgrp** [comment]
`WearVerifyRemoteApp` sample seems to be [intentionally](https://github.com/android/wear-os-samples/blob/6f0df2c49292d13fadacb78fa3bc1d6f3e835218/WearVerifyRemoteApp/Application/src/main/java/com/example/android/wearable/wear/wearverifyremoteapp/MainMobileActivity.kt#L84-L88) using `NodeClient`.

Checking if this is a valid scenario for `NodeClient` to be used and will report back to this issue.

**Comment by luizgrp** [comment]
In a scenario where my watch is connected to my phone, but the watch does NOT have any app with any capability, [CapabilityClient.getAllCapabilities](https://developers.google.com/android/reference/com/google/android/gms/wearable/CapabilityClient#getAllCapabilities(int)) returns an empty map, so I'm not sure it should be replaced there, given it says in the [comment](https://github.com/android/wear-os-samples/blob/6f0df2c49292d13fadacb78fa3bc1d6f3e835218/WearVerifyRemoteApp/Application/src/main/java/com/example/android/wearable/wear/wearverifyremoteapp/MainMobileActivity.kt#L84-L88):

> Initial request for all Wear devices connected (with or without our capability).

@yschimke I'd suggest closing this ticket without any changes, assigning it to you so you can let me know otherwise.
