### ISSUE TITLE
WatchFaceKotlin missing rotary input

### ISSUE THREAD

**Issue by lancelinksp** [android/wear-os-samples#970]
WatchFaceKotlin/app/src/main/res/layout/activity_watch_face_config.xml is using ScrollView but rotary Input is not configured which is part of the [Wear App Quality](https://notifications.google.com/g/p/ANiao5rwjLjDk1NNvj8pJTkA4ZXerV_oMVNnlVIlBZuXrrOt03oSFUJv6MgYZOMuwU68qZVVY7_f6JdnCkAo3cG4aft40lVR_VDHNLh02rek_7AXA6Sz8fA5r-B7wJfFvu7Y68oinNwP8VoDpaq0BVm81SSAlIX5rvSg9tLB_1_jEpq0MNn14aP_Ml4rV4Kama6ipiJTxBzh3JVtNFMv97mxyUi9WayjL5OxWVeOK8akGDtyMAB9Q1Xhg5STEK3kFn4i) Guidelines.

**Comment by derry701** [comment]
@lancelinksp 

I ran into this issue on a personal project and have submitted a pull request with the fix I made

https://github.com/android/wear-os-samples/pull/981

**Comment by kul3r4** [comment]
Closing this as infeasible since as of July 10, 2024, watch faces must use the [Watch Face Format](https://developer.android.com/training/wearables/wff) in order to be installed on new watches that launch with Wear OS 5 pre-installed. See also [https://developer.android.com/training/wearables/watch-faces](https://developer.android.com/training/wearables/watch-faces)
